name: build and test on pull request
on:
  pull_request:
    branches: [master]
jobs:
  #  sast-scan:
  #    runs-on: ubuntu-latest
  #    # Skip any PR created by dependabot to avoid permission issues:
  #    if: (github.actor != 'dependabot[bot]')
  #    steps:
  #      - uses: actions/checkout@v5
  #      - uses: actions/setup-node@v4
  #        with:
  #          node-version: "22"
  #      - run: npm install -g snyk
  #      - run: snyk config set api=${{ secrets.SNYK_API_KEY }}
  #      - run: snyk code test src/main
  malware-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Malware Scanner # https://github.com/dell/common-github-actions/blob/main/malware-scanner/README.md
        uses: dell/common-github-actions/malware-scanner@main
        with:
          directories: .
          options: -ri
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Malware Scanner # https://github.com/dell/common-github-actions/blob/main/malware-scanner/README.md
        uses: dell/common-github-actions/malware-scanner@main
        with:
          directories: .
          options: -ri
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "temurin"
          architecture: x64
      - run: mvn package -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true
