name: build and test on release
on:
  push:
    tags:
      - "*"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "temurin"
          architecture: x64
      - run: mvn package -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true
      - name: "upload release assets"
        uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477 #https://github.com/softprops/action-gh-release/issues/216
        if: github.ref_type == 'tag'
        with:
          body: |
            :closed_book: File 1 of 1 uploaded: junit-xml-merger.jar
          files: |
            target/junit-xml-merger.jar
          append_body: true
