name: scan-codecoverage
on:
  pull_request:
    branches: [main]
jobs:
  scan-codecoverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          architecture: x64
      - run: mvn test
      - run: mvn jacoco:report
      - run:
      - run: zip -r coverage-report-html.zip jacoco/*
        working-directory: target/site/
      - uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: target/site/coverage-report-html.zip
      # runs jacoco check which has 100% coverage rules. see pom.xml
      - run: mvn verify
