name: scan-malware
on:
  pull_request:
    branches: [main]
jobs:
  scan-malware:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Malware Scanner # https://github.com/dell/common-github-actions/blob/main/malware-scanner/README.md
        uses: dell/common-github-actions/malware-scanner@main
        with:
          directories: .
          options: -ri
